### ISSUE TITLE
"Supported Platforms" field for apps

### ISSUE THREAD

**Issue by dhtdht020** [OpenShopChannel/RepositoryManager#2]
Addition of a "supported platforms" field to app manifests should be considered.

To be used for identifying which apps support wii mini, vwii, and regular wiis.

on homebrew browser, long description should possibly be prepended with an applicable "[!! DOES NOT SUPPORT: WII, WII MINI, VWII !!]" prefix, everywhere else, should be exposed through API.

**Comment by Artuto** [comment]
Resolved by https://github.com/OpenShopChannel/RepositoryManager/commit/8093f7c2cbcf31354b0f3538d28ce39112db7f49
